### ISSUE TITLE
Support for Groovy Highlighting

### ISSUE THREAD

**Issue by sdelamo** [farmdawgnation/nova-java-language#2]
I would like to contribute a PR to support [Apache Groovy](https://groovy-lang.org) highlighting. 

Groovy is really close to Java. I think the PR could add some extra keywords (`def`, `as`, etc) and the file extensions `groovy` and `.gradle` for [Gradle](https://gradle.org) builds which use the Groovy DSL.   

Should I create such PR? Would you be interested?

**Comment by farmdawgnation** [comment]
Hey @sdelamo — sorry for the delay in responding. I'd argue that groovy should be its own extension, personally. It's a totally different language with different concepts about how to handle things like Lambdas. I don't pretend to say this extension is _great_ about that at the moment, but those would surely conflict such that you wouldn't be able to reuse much of the syntax I've defined already. Does that seem reasonable?

**Comment by sdelamo** [comment]
Yes, sounds reasonable. However, please note that with Groovy 3, you can write regular Java Lambdas in Groovy with the same syntax. No need to wrap them in a closure syntax anymore as we needed to do with Groovy 2. Groovy 3 makes again going from Java to Groovy really seamless. 

I will fork the repo and probably just add the keywords and extensions for now and publish it as a Groovy Language Highlighting. I am still not familiar with Nova extensions to provide any more features. Since, your extension already provides properties file highlighting I will remove that from the fork.

**Comment by farmdawgnation** [comment]
Cool, I'll close this issue for now but feel free to reopen if you feel this warrants further discussion.
