### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by vtomnet** [farmdawgnation/nova-java-language#7]
Could you please make a release for 1.1.2 so it can be installed through the extension library (when you have time, no pressure :)?
 Thanks!

**Comment by farmdawgnation** [comment]
I’ll aim to do so this weekend kids permitting!On Jul 7, 2023, at 9:26 PM, Tom M ***@***.***> wrote:﻿
Could you please make a release for 1.1.2 so it can be installed through the extension library (when you have time, no pressure :)?
Thanks!

**Comment by farmdawgnation** [comment]
Better late than never, sitting down to look at this now lol

**Comment by farmdawgnation** [comment]
1.1.2 has been released!
